 
title: My GitHub Pages Site
description: A personal website or project page with a dark theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://<your-username>.github.io" # replace with your GitHub Pages URL

theme: jekyll-theme-cayman

# Optional theme tweaks for a dark mode look
# You can use another dark theme like "minimal-dark" if installed manually
# or hosted locally via remote_theme

# Uncomment below if using a remote dark theme from GitHub
# remote_theme: pages-themes/slate@v0.2.0
# plugins:
#   - jekyll-remote-theme

# Other optional settings
markdown: kramdown
highlighter: rouge