title: mdh pages
description: mdh pages
author: Matt Hoendorf

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matthoendorf.github.io" # replace with your GitHub Pages URL

remote_theme: lorepirri/cayman-dark@v1.0.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge